<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [

            // Clothing
            [
                'title' => 'Men Cotton T-Shirt',
                'slug' => Str::slug('Men Cotton T-Shirt'),
                'description' => 'Premium quality 100% cotton T-Shirt for men.',
                'short_description' => 'Soft and comfortable.',
                'shipping_returns' => '3–5 days delivery.',
                'related_products' => null,
                'price' => 450,
                'compare_price' => 550,
                'category_id' => 1,
                'sub_category_id' => 1,
                'brand_id' => 1,
                'is_featured' => 'Yes',
                'sku' => 'TSHIRT-001',
                'barcode' => '123456789012',
                'track_qty' => 'Yes',
                'qty' => 100,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Premium Men Sneakers',
                'slug' => Str::slug('Premium Men Sneakers'),
                'description' => 'Lightweight and stylish sneakers.',
                'short_description' => 'Casual wear shoes.',
                'shipping_returns' => 'Free delivery over 1000 TK.',
                'related_products' => null,
                'price' => 2200,
                'compare_price' => 2800,
                'category_id' => 1,
                'sub_category_id' => 1,
                'brand_id' => 2,
                'is_featured' => 'No',
                'sku' => 'SHOE-244',
                'barcode' => '321654789012',
                'track_qty' => 'Yes',
                'qty' => 60,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Electronics
            [
                'title' => 'Samsung Galaxy A55',
                'slug' => Str::slug('Samsung Galaxy A55'),
                'description' => 'AMOLED display, long battery.',
                'short_description' => 'Official warranty.',
                'shipping_returns' => 'Fast delivery.',
                'related_products' => null,
                'price' => 42000,
                'compare_price' => 45000,
                'category_id' => 2,
                'sub_category_id' => 4,
                'brand_id' => 3,
                'is_featured' => 'Yes',
                'sku' => 'PHONE-101',
                'barcode' => '987654321012',
                'track_qty' => 'Yes',
                'qty' => 50,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Xiaomi 43-inch Smart LED TV',
                'slug' => Str::slug('Xiaomi 43-inch Smart LED TV'),
                'description' => 'Full HD, Android TV.',
                'short_description' => 'Crystal clear picture.',
                'shipping_returns' => 'Comes with 2 year warranty.',
                'related_products' => null,
                'price' => 31000,
                'compare_price' => 35000,
                'category_id' => 2,
                'sub_category_id' => 8,
                'brand_id' => 3,
                'is_featured' => 'No',
                'sku' => 'TV-543',
                'barcode' => '546987321012',
                'track_qty' => 'Yes',
                'qty' => 30,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Apple AirPods 3rd Gen',
                'slug' => Str::slug('Apple AirPods 3rd Gen'),
                'description' => 'Original Apple AirPods.',
                'short_description' => 'Spatial audio, premium sound.',
                'shipping_returns' => '100% authentic.',
                'related_products' => null,
                'price' => 23500,
                'compare_price' => 25000,
                'category_id' => 2,
                'sub_category_id' => 9,
                'brand_id' => 4,
                'is_featured' => 'Yes',
                'sku' => 'AIRPOD-23',
                'barcode' => '998877665544',
                'track_qty' => 'Yes',
                'qty' => 40,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Computer Accessories
            [
                'title' => 'Logitech Gaming Mouse G102',
                'slug' => Str::slug('Logitech Gaming Mouse G102'),
                'description' => 'RGB gaming mouse 8000 DPI.',
                'short_description' => 'Best for gamers.',
                'shipping_returns' => 'Delivery 48 hours.',
                'related_products' => null,
                'price' => 1850,
                'compare_price' => 2200,
                'category_id' => 8,
                'sub_category_id' => 15,
                'brand_id' => 3,
                'is_featured' => 'No',
                'sku' => 'MOUSE-112',
                'barcode' => '885544778899',
                'track_qty' => 'Yes',
                'qty' => 120,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Grocery
            [
                'title' => 'Radhuni Mustard Oil 1L',
                'slug' => Str::slug('Radhuni Mustard Oil 1L'),
                'description' => 'Pure mustard oil for cooking.',
                'short_description' => '100% natural.',
                'shipping_returns' => '24 hours delivery.',
                'related_products' => null,
                'price' => 185,
                'compare_price' => 200,
                'category_id' => 3,
                'sub_category_id' => 7,
                'brand_id' => 7,
                'is_featured' => 'No',
                'sku' => 'OIL-501',
                'barcode' => '456789123654',
                'track_qty' => 'Yes',
                'qty' => 200,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Miniket Rice 5KG',
                'slug' => Str::slug('Miniket Rice 5KG'),
                'description' => 'Premium Miniket rice.',
                'short_description' => 'Fresh and clean.',
                'shipping_returns' => 'Next day delivery.',
                'related_products' => null,
                'price' => 420,
                'compare_price' => 460,
                'category_id' => 3,
                'sub_category_id' => 7,
                'brand_id' => 6,
                'is_featured' => 'No',
                'sku' => 'RICE-005',
                'barcode' => '445566778899',
                'track_qty' => 'Yes',
                'qty' => 300,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Baby Products
            [
                'title' => 'Pampers Baby Diaper Large',
                'slug' => Str::slug('Pampers Baby Diaper Large'),
                'description' => 'Comfortable and safe diapers.',
                'short_description' => 'Super soft.',
                'shipping_returns' => 'Same-day delivery.',
                'related_products' => null,
                'price' => 950,
                'compare_price' => 1100,
                'category_id' => 7,
                'sub_category_id' => 13,
                'brand_id' => 7,
                'is_featured' => 'No',
                'sku' => 'DIAPER-L',
                'barcode' => '556677889900',
                'track_qty' => 'Yes',
                'qty' => 180,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Beauty
            [
                'title' => 'Huda Beauty Makeup Set',
                'slug' => Str::slug('Huda Beauty Makeup Set'),
                'description' => '60+ item premium makeup kit.',
                'short_description' => 'Professional level.',
                'shipping_returns' => 'Delivery within Dhaka.',
                'related_products' => null,
                'price' => 3200,
                'compare_price' => 3600,
                'category_id' => 5,
                'sub_category_id' => 11,
                'brand_id' => 2,
                'is_featured' => 'No',
                'sku' => 'MAKEUP-77',
                'barcode' => '123443211234',
                'track_qty' => 'Yes',
                'qty' => 70,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
